name: deploy1

on:
  
  pull_request:
    branches:
      - main
    paths:
      - 'Project-2/**'
      
  

  

jobs:
  Project1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
        
        
     

